import manifest from './artworks.json';

export type Artwork = {
  id: string;
  src: string;
  title: string;
  width: number;
  height: number;
  blurDataURL: string;
  /** Present only when the source filename encoded it. */
  year?: number;
  /** Present only when the source filename encoded it, e.g. "100 × 80 cm". */
  dimensions?: string;
};

/** Generated by scripts/prepare-artworks.mjs from /sources. Never edited by hand. */
export const artworks: Artwork[] = manifest as Artwork[];
